{{ config(materialized='view') }}

SELECT
    clickId,
    searchId,
    datetime,
    userAgent,
    isInternal,
    operatingSystemWithVersion,
    country,
    city,
    language,
    browserWithVersion,
    username,
    clickRank,
    splitTestRunVersion,
    anonymous,
    documentAuthor,
    browser,
    systemUriHash,
    documentUrl,
    rankingModifier,
    documentCategory,
    userId,
    originContext,
    originLevel3,
    causeV2,
    queryPipeline,
    deviceCategory,
    originLevel2,
    originLevel1,
    sourceName,
    region,
    splitTestRunName,
    clickOriginLevel2,
    clickOriginLevel1,
    collectionName,
    visitorId,
    mobile,
    documentTitle,
    visitId,
    clickCause,
    JSONExtractString(customDatas, 'c_author') as c_author,
    JSONExtractString(customDatas, 'c_product') as c_product,
    JSONExtractString(customDatas, 'c_jsuiversion') as c_jsuiversion,
    JSONExtractString(customDatas, 'c_customvalue') as c_customvalue
FROM {{ source('raw', 'clicks') }}
WHERE clickId IS NOT NULL
  AND datetime IS NOT NULL