{{ config(materialized='view') }}

SELECT
    id,
    datetime,
    userAgent,
    searchIsContextual,
    isInternal,
    actionCause,
    operatingSystemWithVersion,
    country,
    city,
    batchId,
    language,
    browserWithVersion,
    username,
    numberOfResults,
    splitTestRunVersion,
    anonymous,
    browser,
    responseTimeMs,
    searchCustomData,
    searchOriginLevel1,
    searchOriginLevel2,
    withResults,
    userId,
    originContext,
    originLevel3,
    causeV2,
    queryPipeline,
    deviceCategory,
    originLevel2,
    originLevel1,
    region,
    splitTestRunName,
    advancedQueryExpression,
    customDatas,
    visitorId,
    queryExpression,
    withClicks,
    mobile,
    visitId,
    c_jsuiversion,
    c_product,
    c_facetvalue,
    JSONExtractString(searchCustomData, 'c_ipaddress') as c_ipaddress,
    JSONExtractString(customDatas, 'c_product') as c_product_json
FROM {{ source('raw', 'searches') }}
WHERE id IS NOT NULL
  AND datetime IS NOT NULL